// Counts describe named proof obligations or named parameter domains.
// They are never converted into an estimated percentage of research completed.
function progressNumber(q) {
  const parts=String(q).split('/').map(Number); return parts[0]/(parts[1] || 1);
}
function coveragePercent(q) {
  const [numerator,denominator=1n]=String(q).split('/').map(BigInt);
  if (denominator<=0n || numerator<0n || numerator>denominator) throw Error('Invalid coverage fraction');
  if (numerator===denominator) return '100%';
  if (numerator===0n) return '0%';
  const digits=(100n*numerator<denominator || 100n*numerator>99n*denominator) ? 4 : 2;
  const scale=10n**BigInt(digits),rounded=(100n*numerator*scale+denominator/2n)/denominator;
  if (rounded===0n) return '&lt;0.0001%';
  if (rounded===100n*scale) return '&gt;99.9999%';
  return `${rounded/scale}.${String(rounded%scale).padStart(digits,'0')}%`;
}
function proofTally(items) { return `${items.filter(x=>x.status==='proved').length} / ${items.length}`; }
function proofSteps(items) {
  return `<ol class="proof-steps">${items.map(item=>`<li><span class="progress-state ${item.status}">${item.status==='proved'?'Proved':'Open'}</span><div><a href="#${item.link}">${item.label}</a>${item.condition?`<small>${item.condition}</small>`:''}</div></li>`).join('')}</ol>`;
}
function pairAccounting() {
  const groups=SCORE.octahedron.pair_groups;
  return `<div class="pair-accounting" role="img" aria-label="${groups.map(g=>`${g.count} ${g.label}: ${g.status}`).join('; ')}">${groups.map(g=>`<span class="${g.status}" style="flex:${g.count}">${g.count}</span>`).join('')}</div><ul class="pair-key">${groups.map(g=>`<li><span class="progress-state ${g.status}">${g.count}</span><a href="#${g.link}">${g.label}</a> — ${g.status==='conditional'?'conditional reduction':g.status}</li>`).join('')}</ul>`;
}
function boxScope(data,label) {
  return `<details class="progress-domain"><summary>Define ${label}: center, bounds, and certificate</summary><p>The parameters, in order, are (${data.parameter_names.join(', ')}).</p><p>Center: (${data.center.join(', ')}).<br>Independent half-widths: (${data.half_widths.join(', ')}).</p><p>${data.report ? `<a href="../../n6/results/${data.report}">Saved exact verification</a>` : `<a href="../../n6/results/${data.certificate}">Saved partial search (verification pending)</a>`}. Coverage measures volume in these coordinates. It is not a percentage of all shapes of this type.</p></details>`;
}
function coverageGaps() {
  return `<p><b>Two steps are still missing for a complete computational proof:</b></p><ol class="coverage-gaps">${SCORE.coverage_obligations.map(s=>`<li>${s}</li>`).join('')}</ol><p>A geometric theorem could replace this route. Neither missing step has a measured fraction complete.</p>`;
}
function sharpPositionProgress(kind) {
  const groups=SCORE.sharp_positions[kind], names=kind==='minus'?['A','B','C','D','P','Q']:['0','1','2','3','4','5'];
  const open=groups.flatMap(g=>g.patterns.filter(p=>p.status==='open').map(p=>'{'+p.sharp_vertices.map(v=>names[v]).join(', ')+ '}'));
  return `<h4>New map: sharp-vertex positions</h4><p>A sharp vertex has curvature at least 180°. Above the already-proved all-low family:</p><table><thead><tr><th>Sharp vertices</th><th>Position patterns proved</th></tr></thead><tbody>${groups.map(g=>`<tr><td>Exactly ${g.sharp_count}</td><td><b>${g.patterns_proved} / ${g.patterns_total}</b></td></tr>`).join('')}</tbody></table><p><b>${open.length} positional patterns remain:</b> ${open.join(', ')}. These are vertex-position counts, not fractions of shape space. Open patterns can contain proved subfamilies. <a href="#sharp_positions">Read the proof and the exact remaining cases</a>.</p>`;
}
function caseProgress(id,compact=false) {
  const octa=SCORE.octahedron;
  const pairTotal=octa.pair_groups.reduce((n,g)=>n+g.count,0);
  const directlyProved=octa.pair_groups.filter(g=>g.status==='proved').reduce((n,g)=>n+g.count,0);
  const localTotal=octa.pair_groups.filter(g=>g.link==='lemmaL').reduce((n,g)=>n+g.count,0);
  const localProved=octa.pair_groups.filter(g=>g.link==='lemmaL' && g.status==='proved').reduce((n,g)=>n+g.count,0);
  let title,body;
  if (id==='t_octa') {
    title='Octahedron · complete selected-net proof';
    body=`<div class="progress-key"><strong>${directlyProved} / ${pairTotal}</strong><span>face pairs proved for the selected H/R net</span></div><p><a href="#F_chord"><b>Both source-curvature branches are complete</b></a>, including equality and ties. The rule cuts four edges at a maximum-curvature vertex and one edge from its opposite to a maximum-curvature equator vertex.</p><p>This is a written research proof with a dependency audit; independent mathematical review is still needed.</p>`;
    body+=`<p><b>${proofTally(octa.angle_branches)} opposite-petal angle branches proved.</b> <b>${proofTally(octa.patch_regimes)} patch regimes settled under H/R.</b> No selected cut-segment checks remain.</p>${compact?'':proofSteps(octa.source_curvature_branches)+pairAccounting()+proofSteps(octa.angle_branches)+proofSteps(octa.patch_regimes)}`;
    body+=`<p><b>Lemma L is now proved:</b> ${localProved} / ${localTotal} local pairs. The <a href="#F_pole_angle">high-curvature proof</a> and <a href="#F_chord">equal-length proof</a> complete the remaining six pairs.</p>${compact?'':proofSteps(octa.local_curvature_branches)+proofSteps(octa.cut_routes)}`;
    body+=`<p><b><a href="#octa_four_slits">49 / 49 simultaneous-failure classes excluded</a></b> by the selected-net theorem. The earlier enumeration is retained as history; this is not a new computer case count.</p><p><b>Still open:</b> the stronger <a href="#lemmaF">every-slit Lemma F</a> and the two nonsimplicial six-vertex types. The latter need original-edge proofs.</p><p><b>New every-slit progress:</b> <a href="#F_slit_threshold">Every slit with 2κc+κw≥180° is proved safe under H.</a> Also, <a href="#F_low_local">below the curvature threshold, three local checks imply all six far pairs</a>, even without H or R. Slits with a local failure remain open in this stronger question.</p><p><b>Independent positive results:</b> the earlier <a href="#octa_budget">shared angle-budget theorem</a>, curvature arguments, and middle-patch proofs remain available in the retained progress history.</p>`;
  } else if (id==='t_octa_minus') {
    const d=SCORE.minus, first=progressNumber(d.history[0].half_width),last=progressNumber(d.history.at(-1).half_width);
    title='Octahedron minus an edge · two-choice rule to prove';
    body=`<div class="progress-key"><strong>±${last}</strong><span>certified variation in each of 10 coordinates</span></div><p><b>${last/first}× the earlier half-width in every coordinate.</b> The whole current box is certified, including its boundaries.</p><div class="extent-history" aria-label="Verified half-width milestones">${d.history.map((h,i)=>`<span><b>±${progressNumber(h.half_width)}</b><small>${i===0?'Earlier':'Verified'}</small></span>`).join('')}</div><p>${d.leaves} certificate cells · ${d.distinct_cut_trees} cut trees · ${Object.values(d.checked_face_pairs).reduce((a,b)=>a+b,0).toLocaleString()} face-pair checks.</p><p class="global-unknown"><b>Fraction of the whole type covered: unknown.</b> The remaining shapes have not been reduced to a finite list of domains.</p>`;
    body+=`<p><b>Universal proof target: ${d.pattern.proved_classes} / ${d.pattern.proof_classes} classes excluded; ${d.pattern.remaining_classes} remain open.</b> Pinciu's face-neighborhood theorem excludes these classes for every convex realization. <a href="#minus_neighborhood">Read the proof and see all 28 classes</a>.</p><p>The ${d.pattern.candidate_trees}-tree algorithm remains conjectural. Its separate ${d.pattern.holdout_samples.toLocaleString()}-shape numerical holdout is supporting evidence. <a href="#minus_pair">See the algorithm and both 3D cut choices</a>.</p>`;
    if (!compact) body+=`${boxScope(d,'the current minus-edge box')}<details class="progress-domain"><summary>History of the certified extent</summary><div class="progress-table-wrap"><table class="progress-table"><thead><tr><th>Half-width</th><th>Verified cells</th><th>Trees</th><th>Record</th></tr></thead><tbody>${d.history.map(h=>`<tr><td>±${progressNumber(h.half_width)}</td><td>${h.leaves}</td><td>${h.trees}</td><td><a href="../../n6/results/${h.report}">Verification</a></td></tr>`).join('')}</tbody></table></div><p>The last two rows cover exactly the same box. The newer proof uses one fixed tree and 16 cells; the older proof used nine trees and 409 cells. This simplifies the certificate without enlarging its domain. Cell counts do not measure a fraction of the universal proof.</p></details>${coverageGaps()}`;
    body+=`<p class="progress-change"><b>Latest advance: 28 open classes → 21.</b> Seven have a universal exclusion proof. The earlier one-tree, 16-cell certificate still covers the same ±0.05 box.</p>`;
  } else if (id==='t_prismd') {
    const d=SCORE.prism,p=SCORE.prism_partial;
    title='Prism with one diagonal · two named search boxes';
    body=`<div class="box-progress"><div><div class="progress-key"><strong>100%</strong><span>of box A certified</span></div><p>${d.leaves} cells · ${d.distinct_cut_trees} trees · no unresolved cells.</p></div><div><div class="progress-key"><strong>${coveragePercent(p.candidate_parameter_fraction)}</strong><span>of box B provisionally covered</span></div><p>${p.unresolved_cells} unresolved cells occupy ${coveragePercent(p.unresolved_parameter_fraction)} of box B.</p></div></div><p class="progress-pending"><b>Box B: verification pending.</b> Its percentage measures the cells marked successful by the search. Only box A has a completed independent replay.</p><p><b>Boxes A and B have different centers and bounds.</b> These percentages are separate measurements. They must not be added or interpreted as coverage of the whole type.</p><p class="global-unknown"><b>Fraction of the whole type covered: unknown.</b></p>`;
    if (!compact) body+=`${boxScope(d,'box A')}${boxScope(p,'box B')}<p><b>Why count volume?</b> Box B has ${p.candidate_cells.toLocaleString()} candidate-covered cells and ${p.unresolved_cells} unresolved cells, but the candidate-covered cells are tiny. Counting cells equally would suggest ${(100*p.candidate_cells/(p.candidate_cells+p.unresolved_cells)).toFixed(1)}% coverage; their actual parameter volume is only ${coveragePercent(p.candidate_parameter_fraction)}. This fraction is exact bookkeeping of the saved subdivision; the geometric certificates for all these cells have not yet completed independent replay.</p><p><b>What does “${p.unresolved_cells} remaining” mean?</b> It is today's subdivision queue for box B. A difficult cell may split into more cells, so this count can increase even while covered volume grows. It is not a count of all remaining mathematical cases.</p>${coverageGaps()}<p><b>Alternative geometric route:</b> prove that at least one of the two quadrilateral routes at the sharper degree-four apex always works. This is still a conjecture; 60,000 numerical samples do not close it.</p>`;
    body+=`<p class="progress-change">Earlier research hour: <b>box A unchanged</b>; two proposed route rules ruled out exactly. Box B’s saved subdivision is measured here, with geometric replay still pending.</p>`;
  } else return '';
  if (id==='t_octa_minus') body=`<h4>New universal geometric progress</h4><p><b>${proofTally(SCORE.nonsimplicial_curvature_branches)} curvature branches proved.</b> <a href="#nonsimp_flat">Every shape with all curvatures at most 180° has an original-edge net</a>. The branch strictly above 180° has <a href="#original_rule">new original-edge curvature budgets and a sharp-slit Case A reduction</a>; other shapes remain open. These are not equal fractions of shape space.</p>${compact?'':proofSteps(SCORE.nonsimplicial_curvature_branches)}${body}`;
  if (id==='t_prismd') body=`<h4>Three disjoint curvature branches</h4><p><b>${proofTally(SCORE.prism_curvature_branches)} branches proved.</b> The all-low branch is settled. The <a href="#prism_two_sharp">branch with both end vertices sharp</a> is now settled too. Remaining: some vertex is above 180°, while at least one of the two ends is below 180°. Some families there already have proofs. These branch counts are not fractions of shape space.</p>${compact?'':proofSteps(SCORE.prism_curvature_branches)}${body}`;
  if (id==='t_octa_minus' || id==='t_prismd') body=sharpPositionProgress(id==='t_octa_minus'?'minus':'prism')+body;
  return `<section class="case-progress ${compact?'compact':''}" aria-label="${title}"><h3>${compact?`<a href="#${id}">${title}</a>`:title}</h3>${body}${compact?`<a class="progress-more" href="#${id}">See the obligations and precise scope →</a>`:''}</section>`;
}
function progressComparison() {
  const rows=SCORE.snapshots;
  return `<details class="progress-domain progress-comparison"><summary>Retained before-and-after snapshots</summary><div class="progress-table-wrap"><table class="progress-table"><thead><tr><th>Measure</th>${rows.map(r=>`<th>${r.label}</th>`).join('')}</tr></thead><tbody><tr><td>Fully proved six-vertex types</td>${rows.map(r=>`<td>${r.proved_types} / 7</td>`).join('')}</tr><tr><td>Octahedron: angle branches proved</td>${rows.map(r=>`<td>${r.octahedron_angle_branches} / 3</td>`).join('')}</tr><tr><td>Octahedron: local pair obligations proved</td>${rows.map(r=>`<td>${r.octahedron_local_pairs} / 3</td>`).join('')}</tr><tr><td>Minus-edge: certified half-width</td>${rows.map(r=>`<td>±${progressNumber(r.minus_half_width)}</td>`).join('')}</tr><tr><td>Minus-edge: trees used on the same box</td>${rows.map(r=>`<td>${r.minus_trees}</td>`).join('')}</tr><tr><td>Minus-edge: certificate cells</td>${rows.map(r=>`<td>${r.minus_cells}</td>`).join('')}</tr><tr><td>Minus-edge: universal failure classes excluded</td>${rows.map(r=>`<td>${r.minus_classes_excluded===undefined?'—':r.minus_classes_excluded+' / 28'}</td>`).join('')}</tr><tr><td>Prism: certified fraction of box A</td>${rows.map(r=>`<td>${coveragePercent(r.prism_box_A_fraction)}</td>`).join('')}</tr></tbody></table></div><p>The earlier hour added exact counterexamples and a metric-closure obstruction. The later pattern investigation reduced the minus-edge box certificate from nine trees to one and proposed a two-tree universal rule. The newest step excludes seven whole failure classes using the face-neighborhood theorem. The latest snapshots add the complete selected octahedron proof (5/7 whole types) and both nonsimplicial families below 180° maximum curvature. The latter advance does not add another whole type. Earlier columns keep their original counts. <a href="../../n6/CONTINUATION.md">Retained research log</a>.</p></details>`;
}
function minusPairClasses() {
  const d=SCORE.minus.pattern,names=['ACBD','ACP','APQ','ADQ','BDQ','BPQ','BCP'];
  const label=pair=>pair.map(i=>names[i]).join(' / ');
  return `<details class="progress-domain"><summary>All ${d.proof_classes} original classes: ${d.proved_classes} excluded, ${d.remaining_classes} open</summary><p>Each row represents a simultaneous overlap in T_P and T_Q, together with its symmetric counterpart when distinct. Class IDs are retained from the initial investigation.</p><div class="progress-table-wrap"><table class="progress-table"><thead><tr><th>Class</th><th>Overlap in T_P</th><th>Overlap in T_Q</th><th>Status</th></tr></thead><tbody>${d.classes.map(c=>`<tr data-minus-class="${c.id}"><td>${c.id}</td><td>${label(c.orbit[0][0])}</td><td>${label(c.orbit[0][1])}</td><td><span class="chip ${c.status==='open'?'open':'proved'}">${c.status==='open'?'Open':'Excluded'}</span></td></tr>`).join('')}</tbody></table></div><p>These are not equal amounts of proof work or equal regions of shape space. <a href="../../n6/results/minus-pair-proof-progress.json">Exact class list and theorem application</a>.</p></details>`;
}
function progressDashboard(compact=true) {
  const types=children('n6'),done=types.filter(n=>n.status==='proved').length;
  return `<section class="progress-dashboard"><div class="progress-heading"><h2>How far along is the proof?</h2><p><strong>${done} / ${types.length}</strong> six-vertex types proved here · ${types.length-done} remain open</p></div><p class="progress-disclaimer">The indicators below count specific obligations or coverage of a specified box. They do not estimate the percentage of effort or time remaining.</p><div class="type-tally">${types.map(n=>`<a class="${n.status}" href="#${n.id}" title="${n.title}: ${n.status}"><span>${n.status==='proved'?'✓':'○'}</span>${n.title}</a>`).join('')}</div><div class="progress-cards ${compact?'':'expanded'}">${['t_octa','t_octa_minus','t_prismd'].map(id=>caseProgress(id,compact)).join('')}</div>${progressComparison()}${compact?'<p><a href="#progress">Open the full progress dashboard</a></p>':''}</section>`;
}
