const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const notes=path.join(__dirname,'../notes');
const html=fs.readFileSync(path.join(notes,'status.html'),'utf8');
const script=html.match(/<script>([\s\S]*?)<\/script>/)[1];
const ctx=vm.createContext({document:{addEventListener(){}},console});
vm.runInContext(script.slice(0,script.indexOf('let showAll = false;')),ctx);
const score=vm.runInContext('SCORE',ctx),overview=vm.runInContext('progressDashboard()',ctx);
assert.equal(score.octahedron.pair_groups.reduce((n,g)=>n+g.count,0),28);
assert.equal(score.octahedron.pair_groups.filter(g=>g.status==='proved').reduce((n,g)=>n+g.count,0),28);
assert.equal(score.octahedron.pair_groups.find(g=>g.link==='F_hinge').status,'proved');
assert.equal(score.octahedron.angle_branches.filter(g=>g.status==='proved').length,3);
assert.equal(score.octahedron.angle_branches.length,3);
assert.equal(score.octahedron.remaining.length,0);
assert.equal(score.octahedron.patch_regimes.length,5);
assert.equal(score.octahedron.patch_regimes.filter(g=>g.status==='proved').length,5);
assert(overview.includes('5 / 5 patch regimes settled under H/R'));
assert.equal(score.minus.history.at(-1).half_width,score.minus.half_widths[0]);
assert.equal(score.minus.leaves,16);
assert.equal(score.minus.distinct_cut_trees,1);
assert.equal(score.minus.history.at(-2).leaves,409);
assert.equal(score.minus.history.at(-2).trees,9);
assert.equal(score.minus.history.at(-2).half_width,score.minus.history.at(-1).half_width);
assert.equal(score.minus.pattern.candidate_trees,2);
assert.equal(score.minus.pattern.proof_classes,28);
assert.equal(score.minus.pattern.proved_classes,7);
assert.equal(score.minus.pattern.remaining_classes,21);
assert.equal(score.minus.pattern.holdout_samples,10000);
assert.equal(score.minus.pattern.status,'conjecture');
assert.equal(score.snapshots.length,6);
assert.equal(score.snapshots[2].minus_classes_excluded,0);
assert.equal(score.snapshots.at(-1).minus_classes_excluded,7);
assert(score.snapshots.slice(0,4).every(s=>s.proved_types===4 && s.octahedron_local_pairs===0));
assert.equal(score.snapshots.at(-1).proved_types,5);
assert.equal(score.snapshots.at(-1).octahedron_local_pairs,3);
assert.equal(score.snapshots.at(-1).minus_trees,1);
assert.equal(score.snapshots.at(-1).minus_cells,16);
assert.equal(score.prism_partial.verification,'pending');
assert.equal(score.prism_partial.candidate_parameter_fraction,'437/4194304');
assert(overview.includes('0.0104%') && overview.includes('99.9896%'));
assert(overview.includes('Box B: verification pending'));
assert(overview.includes('Fraction of the whole type covered: unknown'));
assert(overview.includes('Independent positive results'));
assert(overview.includes('Retained before-and-after snapshots'));
assert(overview.includes('7 / 28 classes excluded; 21 remain open'));
assert(overview.includes('href="#minus_pair"'));
assert(overview.includes('href="#octa_four_slits"'));
const octaRule=vm.runInContext('article(byId.octa_four_slits,false)',ctx);
assert.equal(vm.runInContext('byId.octa_four_slits.status',ctx),'proved');
assert(octaRule.includes('All 49 simultaneous-failure classes are excluded by the selected-net theorem'));
assert(octaRule.includes('Current rigorous count: 49 classes, 2 excluded, 47 open.'));
assert(octaRule.includes('3,000 sampled octahedra'));
assert(octaRule.includes('not percentages'));
const switching=vm.runInContext('article(byId.octa_switch,false)',ctx);
assert.equal(vm.runInContext('byId.octa_switch.status',ctx),'proved');
assert(switching.includes('S + S′ = 360°'));
assert(switching.includes('original class 49'));
assert(switching.includes('47 open classes'));
assert(switching.includes('remain open'));
assert(switching.includes('now-refuted') || switching.includes('counterexample'));
const failureAnalysis=JSON.parse(fs.readFileSync(path.join(notes,'../../n6/results/octa-failure-analysis.json'),'utf8'));
assert.equal(failureAnalysis.reduced.symmetry_classes,24);
assert.equal(failureAnalysis.geometric_classes_excluded,2);
assert.equal(failureAnalysis.remaining_classes,47);
assert(overview.includes('5 / 7'));
assert(!overview.includes('66.7%'),'Proof branch counts are not completion percentages');
assert.equal(vm.runInContext("coveragePercent('99999999999999999999/100000000000000000000')",ctx),'&gt;99.9999%');
assert.equal(vm.runInContext("coveragePercent('1/100000000000000000000')",ctx),'&lt;0.0001%');
const prism=vm.runInContext('article(byId.t_prismd,false)',ctx);
assert(prism.indexOf('data-model="t_prismd"')<prism.indexOf('Prism with one diagonal · two named search boxes'));
assert(prism.indexOf('data-model="t_prismd"')<prism.indexOf('The proposed reduction'));
assert(prism.indexOf('The proposed reduction')<prism.indexOf('data-model="prism_failure"'));
const detailed=vm.runInContext('progressDashboard(false)',ctx);
assert(detailed.includes('independent mathematical review'));
assert(detailed.includes('3 / 3 local pairs'));
assert(detailed.includes('94.6%'),'Explicitly explain why raw cell counts mislead');
assert(!detailed.includes('undefined') && !detailed.includes('NaN'));
const root=path.join(__dirname,'../..');
for(const m of detailed.matchAll(/href="\.\.\/\.\.\/([^"#]+)(?:#[^"]*)?"/g)) assert(fs.existsSync(path.join(root,m[1])),m[1]);
console.log('Progress: denominators, conditional pairs, provisional coverage, retained snapshots, file links, and prism ordering pass.');

const patches=vm.runInContext('article(byId.octa_patches,false)',ctx);
assert(patches.includes('2 of 49 classes excluded; 47 remain open'));
assert(patches.includes('Two, adjacent') && patches.includes('Two, opposite'));
assert(patches.includes('fixed-source claim remains open'));
assert(patches.includes('two-pole') || patches.includes('exchanges the two poles'));
const curvaturePair=vm.runInContext('article(byId.octa_curvature,false)',ctx);
const shortEdges=vm.runInContext('article(byId.octa_short_edges,false)',ctx);
assert.equal(vm.runInContext('byId.octa_curvature.status',ctx),'proved');
assert(curvaturePair.includes('2 × curvature at v ≥ 360°'));
assert(curvaturePair.includes('Every centrally symmetric octahedron is covered'));
assert(curvaturePair.includes('less sharp pole'));
assert(curvaturePair.includes('2 excluded and 47 open'));
assert(shortEdges.includes('criterion is not universal'));
assert(patches.includes('data-model="octa_patches"'));

const hingeAudit=vm.runInContext('article(byId.F_hinge,false)',ctx);
assert(hingeAudit.includes('27 face pairs are nonoverlapping'));
assert(hingeAudit.includes('not</b> sharpest'));
assert(hingeAudit.includes('data-model="hinge_boundary"'));
assert.equal(failureAnalysis.reduced.sufficient_reduction_valid,false);
assert.equal(failureAnalysis.current.symmetry_classes,49);
const radialCover=vm.runInContext('article(byId.octa_radial_cover,false)',ctx);
assert(radialCover.includes('15-parameter neighborhood'));
assert(radialCover.includes('not a universal characterization'));
const onePatch=vm.runInContext('article(byId.octa_one_patch,false)',ctx);
const halfFan=vm.runInContext('article(byId.octa_half_fan,false)',ctx);
assert.equal(vm.runInContext('byId.octa_one_patch.status',ctx),'proved');
assert(onePatch.includes('both poles have curvature below 180°'));
assert(onePatch.includes('its curvature is above 180°'));
assert(onePatch.includes('2 excluded, 47 open'));
assert(onePatch.includes('data-model="one_patch_A"') && onePatch.includes('data-model="one_patch_B"'));
assert(halfFan.includes('Three direction cases, all proved'));
assert(halfFan.includes('removes the 180° restriction under H'));
assert(overview.includes('shared angle-budget theorem'));
const models=vm.runInContext('FIGS.models',ctx);
assert.deepEqual(models.one_patch_A.P,models.one_patch_B.P);
assert.notDeepEqual(models.one_patch_A.cut,models.one_patch_B.cut);
const budget=vm.runInContext('article(byId.octa_budget,false)',ctx);
const remainingPattern=vm.runInContext('article(byId.octa_three_same,false)',ctx);
assert.equal(vm.runInContext('byId.octa_budget.status',ctx),'proved');
assert.equal(vm.runInContext('byId.octa_three_same.status',ctx),'proved');
assert(remainingPattern.includes('There is no remaining branch of this pattern for the selected H/R rule'));
assert(budget.includes('extension at w + extension at v = inward-corner angle − 180°'));
assert(budget.includes('Four of the five coarse patch regimes'));
assert(budget.includes('2 excluded, 47 open classes'));
assert(budget.includes('data-model="patch_budget"'));
assert(remainingPattern.includes('data-model="three_same"'));
assert(remainingPattern.includes('It does not yet settle every shape'));
assert(remainingPattern.includes('data-model="chain_uncovered"'));
assert(remainingPattern.includes('Outside the older test; nonempty'));
assert(remainingPattern.includes('has not been established here'));
const chain=vm.runInContext('article(byId.octa_three_chain,false)',ctx);
assert.equal(vm.runInContext('byId.octa_three_chain.status',ctx),'proved');
assert(chain.includes('four prescribed trees: two endpoints, at two poles'));
assert(chain.includes('data-model="chain_switch"'));
assert(chain.includes('4 of 5 entire patch regimes'));
assert(chain.includes('2 excluded, 47 open'));
assert(chain.includes('The full octahedron theorem remains open'));
assert.notDeepEqual(models.chain_switch.P,models.chain_uncovered.P);

// The complete local theorem must not silently become a whole-octahedron proof.
assert.equal(score.octahedron.local_curvature_branches.length,3);
assert.equal(score.octahedron.local_curvature_branches.filter(g=>g.status==='proved').length,3);
assert.equal(score.octahedron.pair_groups.find(g=>g.link==='lemmaL').status,'proved');
assert.equal(vm.runInContext('byId.lemmaL.status',ctx),'proved');
assert.equal(vm.runInContext('byId.L_gate.status',ctx),'proved');
const localGate=vm.runInContext('article(byId.L_gate,false)',ctx);
assert(localGate.includes('both strict halves are now settled'));
assert(localGate.includes('3 of 3 universal local pair obligations complete'));
assert(localGate.includes('all 18 coordinates independently by ±0.0001'));
assert(localGate.includes('6/5 as far'));
assert(localGate.includes('data-model="local_gate_chain"'));
assert(overview.includes('Lemma L is now proved'));
assert(detailed.includes('new spherical-link and pole-triangle argument'));
assert(detailed.includes('through-fan bound plus the cut-edge separator'));
assert.deepEqual(models.local_gate_chain.P,models.chain_uncovered.P);
assert.notDeepEqual(models.local_gate_chain.cut,models.chain_uncovered.cut);

const localLemma=vm.runInContext('article(byId.lemmaL,false)',ctx);
assert(localLemma.includes('3 of 3 local pair statements proved'));
assert(localLemma.includes('22 of the selected net’s 28 face pairs'));
assert(localLemma.includes('n=6 and every-slit Lemma F remain open'));
assert(localLemma.includes('cannot automatically be reused there'));
assert(localLemma.includes('lemma-l-cases'));
assert(localLemma.indexOf('Which cases are solved?')<localLemma.indexOf('The slit route: extend'));
assert(!localLemma.slice(localLemma.indexOf('lemma-l-cases'),localLemma.indexOf('What is still open?')).includes('Open in general'));
assert.equal(vm.runInContext('byId.lemmaF.status',ctx),'numeric');
assert.equal(vm.runInContext('byId.t_octa.status',ctx),'proved');

// Coverage now uses the new complete theorem, not merely the earlier reduction.
assert(score.octahedron.remaining.every(g=>g.link==='F_cut_rays'));
assert.equal(vm.runInContext('byId.F_cut_reduction.status',ctx),'proved');
const farLemma=vm.runInContext('article(byId.lemmaF,false)',ctx);
const farReduction=vm.runInContext('article(byId.F_cut_reduction,false)',ctx);
const smallFar=vm.runInContext('article(byId.F_below,false)',ctx);
assert(farLemma.includes('28/28 selected-net pairs are proved'));
assert(farLemma.includes('both H and R'));
assert(farLemma.includes('lemma-f-cases'));
assert(farReduction.includes('the whole selected net is nonoverlapping'));
assert(farReduction.includes('The two retained checks remain open'));
assert(farReduction.includes('slit index k=0'));
assert(smallFar.includes('Before X, or exactly at X'));
assert(smallFar.includes('Past X'));
assert(smallFar.includes('Open in general'));

// The original every-slit and infinite-ray statements remain separate.
const cutRays=vm.runInContext('article(byId.F_cut_rays,false)',ctx);
assert.equal(vm.runInContext('byId.F_cut_rays.status',ctx),'proved');
assert(cutRays.includes('only one segment remains'));
assert(cutRays.includes('finite radial cut segment'));
assert(cutRays.includes('conjectural strengthening'));
assert(cutRays.includes('22/28 face pairs'));
assert(cutRays.includes('Boundary contact is allowed'));
assert(smallFar.includes('Now proved safe'));
assert(smallFar.includes('does not span the blue angle plus the gap'));
assert.equal(score.octahedron.cut_routes.length,2);
assert.equal(score.octahedron.cut_routes.filter(g=>g.status==='proved').length,2);
assert(detailed.includes('No selected cut-segment checks remain'));

// Both curvature branches are complete; the every-slit statement is not.
const poleAngle=vm.runInContext('article(byId.F_pole_angle,false)',ctx);
assert.equal(vm.runInContext('byId.F_pole_angle.status',ctx),'proved');
assert.equal(score.octahedron.source_curvature_branches.length,2);
assert.equal(score.octahedron.source_curvature_branches.filter(g=>g.status==='proved').length,2);
assert(poleAngle.includes('all 28 pairs safe'));
assert(poleAngle.includes('Ties and equality are included'));
assert(poleAngle.includes('every slit'));
assert(poleAngle.includes('strictly between 90° and 120°'));
assert(poleAngle.includes('data-model="far_projection_low"'));
assert(poleAngle.includes('not an overlap'));
assert(poleAngle.includes('joint obstruction is geometrically possible'));
assert(detailed.includes('equal-length proof'));
assert(farLemma.includes('every-slit quantifier remains open'));
assert(smallFar.includes('still obtuse after flattening'));
assert(remainingPattern.includes('new ≥180° theorem now covers'));
const lowCertificate=JSON.parse(fs.readFileSync(path.join(root,'n6/results/far-projection-low-curvature.certificate.json'),'utf8'));
assert.deepEqual(JSON.parse(JSON.stringify(models.far_projection_low.P)),lowCertificate.coordinate_polynomials.map(p=>p.map(c=>Number(c[0][0]))));
assert.deepEqual(JSON.parse(JSON.stringify(models.far_projection_low.cut)),lowCertificate.cut_edges);

const complete=vm.runInContext('article(byId.F_chord,false)',ctx);
assert.equal(vm.runInContext('byId.F_chord.status',ctx),'proved');
assert.equal(score.octahedron.selected_rule.every_slit_lemma_F,'open');
assert.equal(score.octahedron.selected_rule.failure_classes_excluded,49);
assert(complete.includes('Independent mathematical review and formal verification have not been performed'));
assert(complete.includes('Numerical experiments are not proof premises'));
assert(complete.includes('Equality is in both branches'));
assert(complete.includes('all 18 coordinates vary independently'));
assert(complete.includes('data-model="selected_boundary"'));
assert(complete.includes('The full n=6 theorem:</b> still open'));
const boundary=JSON.parse(fs.readFileSync(path.join(root,'n6/results/selected-octahedron-curvature-equality.certificate.json'),'utf8'));
assert.deepEqual(JSON.parse(JSON.stringify(models.selected_boundary.P)),boundary.coordinate_polynomials.map(p=>p.map(c=>Number(c[0][0]))));
assert.deepEqual(JSON.parse(JSON.stringify(models.selected_boundary.cut)),boundary.cut_edges);
for(const id of ['t_octa','octa_four_slits','octa_patches','octa_three_same','lemmaF','F_below','F_pole_angle']) {
  const article=vm.runInContext(`byId.${id}`,ctx);
  assert(article.body.includes('<summary>Earlier investigation, retained with its historical status</summary>'),id);
  const current=article.body.split('<details class="progress-domain">')[0];
  assert(!current.includes('22/28') && !current.includes('47 open'),id);
}

// Whole low-curvature families must not silently include the >=pi boundary,
// prove the old two-choice conjecture, or count another entire six-vertex type.
assert.equal(score.nonsimplicial_curvature_branches.filter(x=>x.status==='proved').length,1);
assert.equal(score.nonsimplicial_curvature_branches.length,2);
assert.equal(vm.runInContext('byId.t_octa_minus.status',ctx),'open');
assert.equal(vm.runInContext('byId.t_prismd.status',ctx),'open');
const lowTypes=vm.runInContext('article(byId.nonsimp_low,false)',ctx);
assert(lowTypes.includes('Maximum curvature exactly 180° or above remains open'));
assert(lowTypes.includes('every artificial diagonal uncut'));
assert(lowTypes.includes('7/28 class count is unchanged'));
assert(lowTypes.includes('four candidate trees') && lowTypes.includes('six original-edge candidate trees'));
assert(lowTypes.includes('data-model="low_minus"') && lowTypes.includes('data-model="low_prism"'));
for(const name of ['minus','prism']) {
  const cert=JSON.parse(fs.readFileSync(path.join(root,`n6/results/low-curvature-${name}.certificate.json`),'utf8'));
  assert.deepEqual(JSON.parse(JSON.stringify(models['low_'+name].P)),cert.coordinate_polynomials.map(p=>p.map(c=>Number(c[0][0]))));
  assert.deepEqual(JSON.parse(JSON.stringify(models['low_'+name].cut)),cert.cut_edges);
  assert.deepEqual(JSON.parse(JSON.stringify(models['low_'+name].faces)),cert.faces);
}

// The new arbitrary-slit result is conditional on all three local pairs.
// It must not silently turn the original every-slit statement into a theorem.
const lowFar=vm.runInContext('article(byId.F_low_local,false)',ctx);
assert.equal(vm.runInContext('byId.F_low_local.status',ctx),'proved');
assert.equal(vm.runInContext('byId.lemmaF.status',ctx),'numeric');
assert.equal(score.octahedron.every_slit_reduction.required_local_pairs,3);
assert.equal(score.octahedron.every_slit_reduction.far_pairs_implied,6);
assert.equal(score.octahedron.every_slit_reduction.unconditional_every_slit_status,'open');
assert(lowFar.includes('a local pair overlaps'));
assert(lowFar.includes('Every-slit far statement remains open'));
assert(lowFar.includes('Neither a sharpest source nor a sharpest slit'));
assert(lowFar.includes('±0.0001'));
assert(farLemma.includes('A far overlap would have to accompany a local overlap'));
assert(detailed.includes('three local checks imply all six far pairs'));
