const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const notes=path.join(__dirname,'../notes');
const html=fs.readFileSync(path.join(notes,'status.html'),'utf8');
const script=html.match(/<script>([\s\S]*?)<\/script>/)[1];
const ctx=vm.createContext({document:{addEventListener(){}},console});
vm.runInContext(script.slice(0,script.indexOf('let showAll = false;')),ctx);
const score=vm.runInContext('SCORE',ctx),overview=vm.runInContext('progressDashboard()',ctx);
assert.equal(score.octahedron.pair_groups.reduce((n,g)=>n+g.count,0),28);
assert.equal(score.octahedron.pair_groups.filter(g=>g.status==='proved').reduce((n,g)=>n+g.count,0),22);
assert.equal(score.octahedron.pair_groups.find(g=>g.link==='F_hinge').status,'open');
assert.equal(score.octahedron.angle_branches.filter(g=>g.status==='proved').length,2);
assert.equal(score.octahedron.angle_branches.length,3);
assert.equal(score.octahedron.remaining.length,2);
assert.equal(score.octahedron.patch_regimes.length,5);
assert.equal(score.octahedron.patch_regimes.filter(g=>g.status==='proved').length,4);
assert(overview.includes('4 / 5 regimes settled under H'));
assert.equal(score.minus.history.at(-1).half_width,score.minus.half_widths[0]);
assert.equal(score.minus.leaves,16);
assert.equal(score.minus.distinct_cut_trees,1);
assert.equal(score.minus.history.at(-2).leaves,409);
assert.equal(score.minus.history.at(-2).trees,9);
assert.equal(score.minus.history.at(-2).half_width,score.minus.history.at(-1).half_width);
assert.equal(score.minus.pattern.candidate_trees,2);
assert.equal(score.minus.pattern.proof_classes,28);
assert.equal(score.minus.pattern.proved_classes,7);
assert.equal(score.minus.pattern.remaining_classes,21);
assert.equal(score.minus.pattern.holdout_samples,10000);
assert.equal(score.minus.pattern.status,'conjecture');
assert.equal(score.snapshots.length,4);
assert.equal(score.snapshots.at(-2).minus_classes_excluded,0);
assert.equal(score.snapshots.at(-1).minus_classes_excluded,7);
assert(score.snapshots.every(s=>s.proved_types===4 && s.octahedron_local_pairs===0));
assert.equal(score.snapshots.at(-1).minus_trees,1);
assert.equal(score.snapshots.at(-1).minus_cells,16);
assert.equal(score.prism_partial.verification,'pending');
assert.equal(score.prism_partial.candidate_parameter_fraction,'437/4194304');
assert(overview.includes('0.0104%') && overview.includes('99.9896%'));
assert(overview.includes('Box B: verification pending'));
assert(overview.includes('Fraction of the whole type covered: unknown'));
assert(overview.includes('Independent positive results'));
assert(overview.includes('Retained before-and-after snapshots'));
assert(overview.includes('7 / 28 classes excluded; 21 remain open'));
assert(overview.includes('href="#minus_pair"'));
assert(overview.includes('href="#octa_four_slits"'));
const octaRule=vm.runInContext('article(byId.octa_four_slits,false)',ctx);
assert.equal(vm.runInContext('byId.octa_four_slits.status',ctx),'open');
assert(octaRule.includes('Current rigorous count: 49 classes, 2 excluded, 47 open.'));
assert(octaRule.includes('3,000 sampled octahedra'));
assert(octaRule.includes('not percentages'));
const switching=vm.runInContext('article(byId.octa_switch,false)',ctx);
assert.equal(vm.runInContext('byId.octa_switch.status',ctx),'proved');
assert(switching.includes('S + S′ = 360°'));
assert(switching.includes('original class 49'));
assert(switching.includes('47 open classes'));
assert(switching.includes('remain open'));
assert(switching.includes('now-refuted') || switching.includes('counterexample'));
const failureAnalysis=JSON.parse(fs.readFileSync(path.join(notes,'../../n6/results/octa-failure-analysis.json'),'utf8'));
assert.equal(failureAnalysis.reduced.symmetry_classes,24);
assert.equal(failureAnalysis.geometric_classes_excluded,2);
assert.equal(failureAnalysis.remaining_classes,47);
assert(overview.includes('4 / 7'));
assert(!overview.includes('66.7%'),'Proof branch counts are not completion percentages');
assert.equal(vm.runInContext("coveragePercent('99999999999999999999/100000000000000000000')",ctx),'&gt;99.9999%');
assert.equal(vm.runInContext("coveragePercent('1/100000000000000000000')",ctx),'&lt;0.0001%');
const prism=vm.runInContext('article(byId.t_prismd,false)',ctx);
assert(prism.indexOf('data-model="t_prismd"')<prism.indexOf('Prism with one diagonal · two named search boxes'));
assert(prism.indexOf('data-model="t_prismd"')<prism.indexOf('The proposed reduction'));
assert(prism.indexOf('The proposed reduction')<prism.indexOf('data-model="prism_failure"'));
const detailed=vm.runInContext('progressDashboard(false)',ctx);
assert(detailed.includes('older reduction') && detailed.includes('refuted'));
assert(detailed.includes('3 / 3 local pair obligations'));
assert(detailed.includes('94.6%'),'Explicitly explain why raw cell counts mislead');
assert(!detailed.includes('undefined') && !detailed.includes('NaN'));
const root=path.join(__dirname,'../..');
for(const m of detailed.matchAll(/href="\.\.\/\.\.\/([^"#]+)(?:#[^"]*)?"/g)) assert(fs.existsSync(path.join(root,m[1])),m[1]);
console.log('Progress: denominators, conditional pairs, provisional coverage, retained snapshots, file links, and prism ordering pass.');

const patches=vm.runInContext('article(byId.octa_patches,false)',ctx);
assert(patches.includes('2 of 49 classes excluded; 47 remain open'));
assert(patches.includes('Two, adjacent') && patches.includes('Two, opposite'));
assert(patches.includes('fixed-source claim remains open'));
assert(patches.includes('two-pole') || patches.includes('exchanges the two poles'));
const curvaturePair=vm.runInContext('article(byId.octa_curvature,false)',ctx);
const shortEdges=vm.runInContext('article(byId.octa_short_edges,false)',ctx);
assert.equal(vm.runInContext('byId.octa_curvature.status',ctx),'proved');
assert(curvaturePair.includes('2 × curvature at v ≥ 360°'));
assert(curvaturePair.includes('Every centrally symmetric octahedron is covered'));
assert(curvaturePair.includes('less sharp pole'));
assert(curvaturePair.includes('2 excluded and 47 open'));
assert(shortEdges.includes('criterion is not universal'));
assert(patches.includes('data-model="octa_patches"'));

const hingeAudit=vm.runInContext('article(byId.F_hinge,false)',ctx);
assert(hingeAudit.includes('27 face pairs are nonoverlapping'));
assert(hingeAudit.includes('not</b> sharpest'));
assert(hingeAudit.includes('data-model="hinge_boundary"'));
assert.equal(failureAnalysis.reduced.sufficient_reduction_valid,false);
assert.equal(failureAnalysis.current.symmetry_classes,49);
const radialCover=vm.runInContext('article(byId.octa_radial_cover,false)',ctx);
assert(radialCover.includes('15-parameter neighborhood'));
assert(radialCover.includes('not a universal characterization'));
const onePatch=vm.runInContext('article(byId.octa_one_patch,false)',ctx);
const halfFan=vm.runInContext('article(byId.octa_half_fan,false)',ctx);
assert.equal(vm.runInContext('byId.octa_one_patch.status',ctx),'proved');
assert(onePatch.includes('both poles have curvature below 180°'));
assert(onePatch.includes('its curvature is above 180°'));
assert(onePatch.includes('2 excluded, 47 open'));
assert(onePatch.includes('data-model="one_patch_A"') && onePatch.includes('data-model="one_patch_B"'));
assert(halfFan.includes('Three direction cases, all proved'));
assert(halfFan.includes('removes the 180° restriction under H'));
assert(overview.includes('shared angle-budget theorem'));
const models=vm.runInContext('FIGS.models',ctx);
assert.deepEqual(models.one_patch_A.P,models.one_patch_B.P);
assert.notDeepEqual(models.one_patch_A.cut,models.one_patch_B.cut);
const budget=vm.runInContext('article(byId.octa_budget,false)',ctx);
const remainingPattern=vm.runInContext('article(byId.octa_three_same,false)',ctx);
assert.equal(vm.runInContext('byId.octa_budget.status',ctx),'proved');
assert.equal(vm.runInContext('byId.octa_three_same.status',ctx),'open');
assert(budget.includes('extension at w + extension at v = inward-corner angle − 180°'));
assert(budget.includes('Four of the five coarse patch regimes'));
assert(budget.includes('2 excluded, 47 open classes'));
assert(budget.includes('data-model="patch_budget"'));
assert(remainingPattern.includes('data-model="three_same"'));
assert(remainingPattern.includes('It does not yet settle every shape'));
assert(remainingPattern.includes('data-model="chain_uncovered"'));
assert(remainingPattern.includes('Open and nonempty'));
assert(remainingPattern.includes('has not been established here'));
const chain=vm.runInContext('article(byId.octa_three_chain,false)',ctx);
assert.equal(vm.runInContext('byId.octa_three_chain.status',ctx),'proved');
assert(chain.includes('four prescribed trees: two endpoints, at two poles'));
assert(chain.includes('data-model="chain_switch"'));
assert(chain.includes('4 of 5 entire patch regimes'));
assert(chain.includes('2 excluded, 47 open'));
assert(chain.includes('The full octahedron theorem remains open'));
assert.notDeepEqual(models.chain_switch.P,models.chain_uncovered.P);

// The complete local theorem must not silently become a whole-octahedron proof.
assert.equal(score.octahedron.local_curvature_branches.length,3);
assert.equal(score.octahedron.local_curvature_branches.filter(g=>g.status==='proved').length,3);
assert.equal(score.octahedron.pair_groups.find(g=>g.link==='lemmaL').status,'proved');
assert.equal(vm.runInContext('byId.lemmaL.status',ctx),'proved');
assert.equal(vm.runInContext('byId.L_gate.status',ctx),'proved');
const localGate=vm.runInContext('article(byId.L_gate,false)',ctx);
assert(localGate.includes('both strict halves are now settled'));
assert(localGate.includes('3 of 3 universal local pair obligations complete'));
assert(localGate.includes('all 18 coordinates independently by ±0.0001'));
assert(localGate.includes('6/5 as far'));
assert(localGate.includes('data-model="local_gate_chain"'));
assert(overview.includes('Lemma L is now proved'));
assert(detailed.includes('new spherical-link and pole-triangle argument'));
assert(detailed.includes('through-fan bound plus the cut-edge separator'));
assert.deepEqual(models.local_gate_chain.P,models.chain_uncovered.P);
assert.notDeepEqual(models.local_gate_chain.cut,models.chain_uncovered.cut);

const localLemma=vm.runInContext('article(byId.lemmaL,false)',ctx);
assert(localLemma.includes('3 of 3 local pair statements proved'));
assert(localLemma.includes('22 of the selected net’s 28 face pairs'));
assert(localLemma.includes('The full octahedron and n=6 remain open'));
assert(localLemma.includes('cannot automatically be reused there'));
assert(localLemma.includes('lemma-l-cases'));
assert(localLemma.indexOf('Which cases are solved?')<localLemma.indexOf('The slit route: extend'));
assert(!localLemma.slice(localLemma.indexOf('lemma-l-cases'),localLemma.indexOf('What is still open?')).includes('Open in general'));
assert.equal(vm.runInContext('byId.lemmaF.status',ctx),'numeric');
assert.equal(vm.runInContext('byId.t_octa.status',ctx),'open');

// A sufficient two-pair reduction must not inflate unconditional coverage.
assert(score.octahedron.remaining.every(g=>g.link==='F_cut_rays'));
assert.equal(vm.runInContext('byId.F_cut_reduction.status',ctx),'proved');
const farLemma=vm.runInContext('article(byId.lemmaF,false)',ctx);
const farReduction=vm.runInContext('article(byId.F_cut_reduction,false)',ctx);
const smallFar=vm.runInContext('article(byId.F_below,false)',ctx);
assert(farLemma.includes('22/28 pairs remain proved unconditionally'));
assert(farLemma.includes('both H and R'));
assert(farLemma.includes('lemma-f-cases'));
assert(farReduction.includes('the whole selected net is nonoverlapping'));
assert(farReduction.includes('The two retained checks remain open'));
assert(farReduction.includes('slit index k=0'));
assert(smallFar.includes('Before X, or exactly at X'));
assert(smallFar.includes('Past X'));
assert(smallFar.includes('Open in general'));

// New subcases and simpler obligations must keep the universal theorem open.
const cutRays=vm.runInContext('article(byId.F_cut_rays,false)',ctx);
assert.equal(vm.runInContext('byId.F_cut_rays.status',ctx),'proved');
assert(cutRays.includes('only one segment remains'));
assert(cutRays.includes('finite radial cut segment'));
assert(cutRays.includes('conjectural strengthening'));
assert(cutRays.includes('22/28 face pairs'));
assert(cutRays.includes('Boundary contact is allowed'));
assert(smallFar.includes('Now proved safe'));
assert(smallFar.includes('does not span the blue angle plus the gap'));
assert.equal(score.octahedron.cut_routes.length,2);
assert.equal(score.octahedron.cut_routes.filter(g=>g.status==='proved').length,1);
assert(detailed.includes('one cut-segment check'));
