const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const notes=path.join(__dirname,'../notes');
const html=fs.readFileSync(path.join(notes,'status.html'),'utf8');
const script=html.match(/<script>([\s\S]*?)<\/script>/)[1];
const ctx=vm.createContext({document:{addEventListener(){}},console});
vm.runInContext(script.slice(0,script.indexOf('let showAll = false;')),ctx);
const score=vm.runInContext('SCORE',ctx),overview=vm.runInContext('progressDashboard()',ctx);
assert.equal(score.octahedron.pair_groups.reduce((n,g)=>n+g.count,0),28);
assert.equal(score.octahedron.pair_groups.filter(g=>g.status==='proved').reduce((n,g)=>n+g.count,0),19);
assert.equal(score.octahedron.pair_groups.find(g=>g.link==='F_hinge').status,'open');
assert.equal(score.octahedron.angle_branches.filter(g=>g.status==='proved').length,2);
assert.equal(score.octahedron.angle_branches.length,3);
assert.equal(score.octahedron.remaining.length,3);
assert.equal(score.minus.history.at(-1).half_width,score.minus.half_widths[0]);
assert.equal(score.minus.leaves,16);
assert.equal(score.minus.distinct_cut_trees,1);
assert.equal(score.minus.history.at(-2).leaves,409);
assert.equal(score.minus.history.at(-2).trees,9);
assert.equal(score.minus.history.at(-2).half_width,score.minus.history.at(-1).half_width);
assert.equal(score.minus.pattern.candidate_trees,2);
assert.equal(score.minus.pattern.proof_classes,28);
assert.equal(score.minus.pattern.proved_classes,7);
assert.equal(score.minus.pattern.remaining_classes,21);
assert.equal(score.minus.pattern.holdout_samples,10000);
assert.equal(score.minus.pattern.status,'conjecture');
assert.equal(score.snapshots.length,4);
assert.equal(score.snapshots.at(-2).minus_classes_excluded,0);
assert.equal(score.snapshots.at(-1).minus_classes_excluded,7);
assert(score.snapshots.every(s=>s.proved_types===4 && s.octahedron_local_pairs===0));
assert.equal(score.snapshots.at(-1).minus_trees,1);
assert.equal(score.snapshots.at(-1).minus_cells,16);
assert.equal(score.prism_partial.verification,'pending');
assert.equal(score.prism_partial.candidate_parameter_fraction,'437/4194304');
assert(overview.includes('0.0104%') && overview.includes('99.9896%'));
assert(overview.includes('Box B: verification pending'));
assert(overview.includes('Fraction of the whole type covered: unknown'));
assert(overview.includes('Independent positive results'));
assert(overview.includes('Retained before-and-after snapshots'));
assert(overview.includes('7 / 28 classes excluded; 21 remain open'));
assert(overview.includes('href="#minus_pair"'));
assert(overview.includes('href="#octa_four_slits"'));
const octaRule=vm.runInContext('article(byId.octa_four_slits,false)',ctx);
assert.equal(vm.runInContext('byId.octa_four_slits.status',ctx),'open');
assert(octaRule.includes('Current rigorous count: 49 classes, 2 excluded, 47 open.'));
assert(octaRule.includes('3,000 sampled octahedra'));
assert(octaRule.includes('not percentages'));
const switching=vm.runInContext('article(byId.octa_switch,false)',ctx);
assert.equal(vm.runInContext('byId.octa_switch.status',ctx),'proved');
assert(switching.includes('S + S′ = 360°'));
assert(switching.includes('original class 49'));
assert(switching.includes('47 open classes'));
assert(switching.includes('remain open'));
assert(switching.includes('now-refuted') || switching.includes('counterexample'));
const failureAnalysis=JSON.parse(fs.readFileSync(path.join(notes,'../../n6/results/octa-failure-analysis.json'),'utf8'));
assert.equal(failureAnalysis.reduced.symmetry_classes,24);
assert.equal(failureAnalysis.geometric_classes_excluded,2);
assert.equal(failureAnalysis.remaining_classes,47);
assert(overview.includes('4 / 7'));
assert(!overview.includes('66.7%'),'Proof branch counts are not completion percentages');
assert.equal(vm.runInContext("coveragePercent('99999999999999999999/100000000000000000000')",ctx),'&gt;99.9999%');
assert.equal(vm.runInContext("coveragePercent('1/100000000000000000000')",ctx),'&lt;0.0001%');
const prism=vm.runInContext('article(byId.t_prismd,false)',ctx);
assert(prism.indexOf('data-model="t_prismd"')<prism.indexOf('Prism with one diagonal · two named search boxes'));
assert(prism.indexOf('data-model="t_prismd"')<prism.indexOf('The proposed reduction'));
assert(prism.indexOf('The proposed reduction')<prism.indexOf('data-model="prism_failure"'));
const detailed=vm.runInContext('progressDashboard(false)',ctx);
assert(detailed.includes('old reduction') && detailed.includes('refuted'));
assert(detailed.includes('0 / 3 local pair obligations'));
assert(detailed.includes('94.6%'),'Explicitly explain why raw cell counts mislead');
assert(!detailed.includes('undefined') && !detailed.includes('NaN'));
const root=path.join(__dirname,'../..');
for(const m of detailed.matchAll(/href="\.\.\/\.\.\/([^"#]+)(?:#[^"]*)?"/g)) assert(fs.existsSync(path.join(root,m[1])),m[1]);
console.log('Progress: denominators, conditional pairs, provisional coverage, retained snapshots, file links, and prism ordering pass.');

const patches=vm.runInContext('article(byId.octa_patches,false)',ctx);
assert(patches.includes('2 of 49 classes excluded; 47 remain open'));
assert(patches.includes('Two, adjacent') && patches.includes('Two, opposite'));
assert(patches.includes('Whole-net safety in this regime is therefore reopened'));
const curvaturePair=vm.runInContext('article(byId.octa_curvature,false)',ctx);
const shortEdges=vm.runInContext('article(byId.octa_short_edges,false)',ctx);
assert.equal(vm.runInContext('byId.octa_curvature.status',ctx),'proved');
assert(curvaturePair.includes('2 × curvature at v ≥ 360°'));
assert(curvaturePair.includes('Every centrally symmetric octahedron is covered'));
assert(curvaturePair.includes('less sharp pole'));
assert(curvaturePair.includes('2 excluded and 47 open'));
assert(shortEdges.includes('criterion is not universal'));
assert(patches.includes('data-model="octa_patches"'));

const hingeAudit=vm.runInContext('article(byId.F_hinge,false)',ctx);
assert(hingeAudit.includes('27 face pairs are nonoverlapping'));
assert(hingeAudit.includes('not</b> sharpest'));
assert(hingeAudit.includes('data-model="hinge_boundary"'));
assert.equal(failureAnalysis.reduced.sufficient_reduction_valid,false);
assert.equal(failureAnalysis.current.symmetry_classes,49);
const radialCover=vm.runInContext('article(byId.octa_radial_cover,false)',ctx);
assert(radialCover.includes('15-parameter neighborhood'));
assert(radialCover.includes('not a universal characterization'));
